services:
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube_container
    ports:
      - "9002:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    restart: unless-stopped

  tester:
    build: .
    container_name: java_tester_container
    volumes:
      - ./workspace:/app/workspace
      - ./cloned_repo:/app/cloned_repo
      - maven_cache:/var/maven/.m2
    restart: unless-stopped
    working_dir: /app
    depends_on:
      - sonarqube

volumes:
  maven_cache:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
